# general settings
name: ablation_2branches_light_x4
model_type: DATModel
scale: 4
num_gpu: 1
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    task: SR
    name: DF2K
    type: PairedImageDataset
    dataroot_gt: H:\VOCCrop\Flickr2K\Flickr2K\Flickr2K_train_HR.lmdb
    dataroot_lq: H:\VOCCrop\Flickr2K\Flickr2K\Flickr2K_train_LR\X4.lmdb
    filename_tmpl: '{}'
    io_backend:
      type: lmdb

    gt_size: 192
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: True
    num_worker_per_gpu: 12
    batch_size_per_gpu: 8
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

    #use_shuffle: true
    #num_worker_per_gpu: 4
    #batch_size_per_gpu: 16
    #dataset_enlarge_ratio: 100
    #prefetch_mode: ~

  val:
    task: SR
    name: Set14
    type: PairedImageDataset
    dataroot_gt: C:\Users\lzhan\Desktop\sisr\SISR\BSRN\BSRN\datasets\Set14\GTmod4
    dataroot_lq: C:\Users\lzhan\Desktop\sisr\SISR\BSRN\BSRN\datasets\Set14\LRbicx4
    filename_tmpl: '{}'
    io_backend:
      type: disk


# network structures
network_g:
  type: DAT
  upscale: 4
  in_chans: 3
  img_size: 64
  img_range: 1.
  depth: [8]
  embed_dim: 60
  num_heads: [6]
  expansion_factor: 2
  resi_connection: '3conv'
  split_size: [8,32]
  upsampler: 'pixelshuffledirect'

# path
path:
  pretrain_network_g: ~
  strict_load_g: False
  resume_state: ~

# training settings
train:
  #optim_g:
    #type: Adam
    #lr: !!float 1e-3
    #weight_decay: 0
    #betas: [0.9, 0.999]

  optim_g:
    type: Adam
    lr: !!float 1e-3
    #lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.999]


  scheduler:
    type: CosineAnnealingRestartLR
    periods: [1000000]
    restart_weights: [1]
    eta_min: !!float 1e-7

  #optim_g:
    #type: Adam
    #lr: !!float 2e-4
    #weight_decay: 0
    #betas: [0.9, 0.99]

  #scheduler:
    #type: MultiStepLR
    #milestones: [250000, 400000, 450000, 475000]
    #gamma: 0.5

  #total_iter: 2000000
  #warmup_iter: -1  # no warm up

  total_iter: 1000000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean


# validation settings
val:
  val_freq: !!float 1e3
  save_img: False

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 4
      test_y_channel: True

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 1e3
  use_tb_logger: True
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
