# general settings
name: train_DAT_light_x2
model_type: DATModel
scale: 2
num_gpu: auto
manual_seed: 10

# dataset and data loader settings
datasets:
  train:
    task: SR
    name: DF2K
    type: PairedImageDataset
    dataroot_gt: H:\VOCCrop\Flickr2K\Flickr2K\Flickr2K_HR.lmdb
    dataroot_lq: H:\VOCCrop\Flickr2K\Flickr2K\Flickr2K_LR_bicubic\X2.lmdb
    filename_tmpl: '{}'
    io_backend:
      type: lmdb

    gt_size: 96
    use_hflip: True
    use_rot: True

    # data loader
    #use_shuffle: True
    #num_worker_per_gpu: 12
    #batch_size_per_gpu: 8
    #dataset_enlarge_ratio: 1
    #prefetch_mode: ~

    use_shuffle: true
    num_worker_per_gpu: 3
    batch_size_per_gpu: 16
    dataset_enlarge_ratio: 100
    prefetch_mode: ~

  val:
    task: SR
    name: Set5
    type: PairedImageDataset
    dataroot_gt: C:\Users\lzhan\Desktop\sisr\SISR\BSRN\BSRN\datasets\Set5\GTmod4
    dataroot_lq: C:\Users\lzhan\Desktop\sisr\SISR\BSRN\BSRN\datasets\Set5\LRbicx2
    filename_tmpl: '{}'
    io_backend:
      type: disk

# network structures
network_g:
  type: DAT
  upscale: 2
  in_chans: 3
  img_size: 64
  img_range: 1.
  depth: [8]
  embed_dim: 60
  num_heads: [6]
  expansion_factor: 2
  resi_connection: '3conv'
  split_size: [8,32]
  upsampler: 'pixelshuffledirect'

# path
path:
  pretrain_network_g: ~
  strict_load_g: True
  resume_state: ~

# training settings
train:
  optim_g:
    type: Adam
    lr: !!float 1e-3
    weight_decay: 0
    betas: [0.9, 0.99]

  #scheduler:
    #type: MultiStepLR
    #milestones: [250000, 400000, 450000, 475000]
    #gamma: 0.5

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [2000000]
    restart_weights: [1]
    eta_min: !!float 1e-7

  total_iter: 2000000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 1e3
  save_img: False

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 2
      test_y_channel: True

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 1e3
  use_tb_logger: True
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
